services:
  php:
    build: .
    container_name: php-container
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER y MYSQL_PASSWORD han sido removidos ya que son para usuarios regulares
    volumes:
      - db_data:/var/lib/mysql
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql # Montar el archivo SQL aquí

volumes:
  db_data:
