services:
  php:
    build: .
    container_name: php-container
    ports:
      - "${APP_PORT:-80}:80"  # Usa el puerto definido en .env o 80 por defecto
    volumes:
      - ./:/var/www/html       # Monta el directorio actual en el contenedor
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf # Asegura la configuración de Apache
      - ./php.ini:/usr/local/etc/php/php.ini  # Monta el php.ini para editarlo sin reconstruir
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Define esta variable en .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Define esta variable en .env
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Asegura que el archivo init.sql exista

volumes:
  db_data:
